    //
// Created by isake on 25/11/2021.
//

#ifndef RECRUITMENT_IER_EDLF_FACTORYCANDIDATO_H
#define RECRUITMENT_IER_EDLF_FACTORYCANDIDATO_H


class FactoryCandidato {

};


#endif //RECRUITMENT_IER_EDLF_FACTORYCANDIDATO_H
